### ISSUE TITLE
Misassemblies report and unaligned report

### ISSUE THREAD

**Issue by RootQJZ** [ablab/quast#51] opened 2018-02-05 20:07 UTC
Hi,

Thanks for the great program!

When I was running metaQuast with a list of reference, the output only contains summary report with no misassembly to reference informations and report. I am wondering how to get the misassembly (to reference) information.

Any ideas?

**Comment by alexeigurevich** [comment] 2018-02-05 20:18
Hi!
Could you attach here your metaquast.log file from the output directory?

**Comment by RootQJZ** [comment] 2018-02-05 20:34
Hi!

The first log file used a list of references(about 50 genomes) and second log file used one single reference:

[metaquast_1.log](https://github.com/ablab/quast/files/1696681/metaquast_1.log)
[metaquast_2.log](https://github.com/ablab/quast/files/1696682/metaquast_2.log)

Thanks!

**Comment by alexeigurevich** [comment] 2018-02-05 20:37
Something is with the alignment step. Could you please also attach
/Users/ZQJ/Downloads/quast-4.6.2/quast_results/results_2018_02_05_12_50_25/combined_reference/quast.log
and 
/Users/ZQJ/Downloads/quast-4.6.2/quast_results/results_2018_02_05_14_26_53/combined_reference/quast.log

**Comment by RootQJZ** [comment] 2018-02-05 20:40
Hi,

Here are two quast log file:

[quast_1.log](https://github.com/ablab/quast/files/1696696/quast_1.log)
[quast_2.log](https://github.com/ablab/quast/files/1696697/quast_2.log)

Thanks!

**Comment by alexeigurevich** [comment] 2018-02-05 20:45
Thanks! Now we are closer.
Could you please run `quast.py --test` to ensure that the alignment software is properly installed. Send me `quast.log` from `quast_test_output` dir after that.
Also, 
/Users/ZQJ/Downloads/quast-4.6.2/quast_results/results_2018_02_05_14_26_53/combined_reference/contigs_reports/contigs_report_metaspades_sample100_contigs.stderr may be helpful for understanding the problem.

**Comment by RootQJZ** [comment] 2018-02-05 20:51
Hi,

I think there an error when running the test and here is the quast.log from quast_test_output dir:

[quast.log](https://github.com/ablab/quast/files/1696728/quast.log)

Thanks!

**Comment by alexeigurevich** [comment] 2018-02-05 21:12
Yep, 
It looks like a bug specifically in release 4.6.2. We will fix it in 4.6.3 which will be available really soon (in 1-2 days). By the way, could you rerun your metaquast runs with `--force-nucmer` option and check whether you finally get the alignment step passed or not (you can attach the new metaquast.log or just check whether you get reports with number of misassemblies, etc).

**Comment by RootQJZ** [comment] 2018-02-05 22:00
Hi,

I rerun with the command: ./metaquast.py -R ../Bacteroides_uniformis.fasta --force-nucmer ../metaspades_sample100_contigs.fasta and got the alignment step. Here is the log file:

[metaquast.log](https://github.com/ablab/quast/files/1696932/metaquast.log)

Thanks!

**Comment by alexeigurevich** [comment] 2018-02-06 08:49
Hi,
Great, than use `--force-nucmer` always in your runs. The problem is related to E-MEM aligner which is a faster version of Nucmer but it has many dependency issues and probably cannot be properly installed on your machine. Do not worry about it -- the output of Nucmer and E-MEM are absolutely equivalent, so the difference is in speed only and it is not very significant.
I am closing the issue now and thank you for reporting the bug with `--test` -- it will help us to improve the upcoming 4.6.3 bugfix release.

Note that we are working on the next major release (5.0) which will use another aligner (minimap2), so this E-MEM-installation issues become completely obsolete.

**Closed by alexeigurevich** 2018-02-06 08:49 UTC

**Comment by alexeigurevich** [comment] 2018-02-06 16:06
JFYI: v4.6.3 is officially released on sourceforge: https://sourceforge.net/projects/quast/files/
However, your E-MEM problem will not probably fixed by this release since it is most likely a dependancies issue.

**Comment by RootQJZ** [comment] 2018-02-06 16:07
Thanks so much!
