### ISSUE TITLE
MetaQuast Summary Error

### ISSUE THREAD

**Issue by pbelmann** [ablab/quast#6] opened 2015-08-04 12:54 UTC
Hi, 

metaquast is great piece of software, but I receive an error in the new version 3.0:

Command:
```
python /usr/local/quast/metaquast.py $LABELS $REFERENCES --scaffolds --output-dir $WORK_DIR $CONTIGS  
```

metaquast.log:

```
.
.
.
Summarizing results...

'adoring_jones broken' is not in list
Traceback (most recent call last):
  File "/usr/local/quast/metaquast.py", line 708, in <module>
    return_code = main(sys.argv[1:])
  File "/usr/local/quast/metaquast.py", line 695, in main
    create_meta_summary.do(output_dirpath, summary_dirpath, labels, metrics_for_plots, misassembl_metrics, ref_names)
  File "/usr/local/quast/libs/create_meta_summary.py", line 59, in do
    results, all_rows, cur_ref_names = get_results_for_metric(ref_names, metric, contigs_num, labels, output_dirpath, qconfig.transposed_report_prefix + '.tsv')
  File "/usr/local/quast/libs/create_meta_summary.py", line 41, in get_results_for_metric
    index_contig = labels.index(values[0])
ValueError: 'adoring_jones broken' is not in list

```

**Comment by alexeigurevich** [comment] 2015-08-04 14:41
Hi Peter, 
Thanks for noticing this bug! We already fixed it and the fix will be included in MetaQuast 3.1which we plan to release by the end of this week. 
You can check out release_3.1 branch now. 

The bug occured only in case number of references is less than number of assemblies (which is not common for metagenomes actually).

**Closed by alexeigurevich** 2015-08-04 14:41 UTC

**Comment by pbelmann** [comment] 2015-08-04 16:54
Thank you Alexey  for the fast answer but I just checked out the 3.1 version and I think this time it is another bug:

```
[Errno 2] No such file or directory: '/home/pbelmann/metrics/workspace/5489634d60b2b261463f0207/bioboxes/quast/cache/not_aligned_quast_output/transposed_report.tsv'
Traceback (most recent call last):
  File "/usr/local/quast/metaquast.py", line 706, in <module>
    return_code = main(sys.argv[1:])
  File "/usr/local/quast/metaquast.py", line 694, in main
    create_meta_summary.do(output_dirpath, summary_dirpath, metrics_for_plots, misassembl_metrics, ref_names)
  File "/usr/local/quast/libs/create_meta_summary.py", line 75, in do
    results, all_rows, cur_ref_names = get_results_for_metric(ref_names, metric, contigs_num, labels, output_dirpath, qconfig.transposed_report_prefix + '.tsv')
  File "/usr/local/quast/libs/create_meta_summary.py", line 30, in get_results_for_metric
    results_file = open(results_fpath, 'r')
IOError: [Errno 2] No such file or directory: '/home/pbelmann/metrics/workspace/5489634d60b2b261463f0207/bioboxes/quast/cache/not_aligned_quast_output/transposed_report.tsv'
```

I'm using about 20 references and two assembly files.

**Comment by alexeigurevich** [comment] 2015-08-04 18:25
Peter, thanks again! Sorry for the inconvenience it was our fault, the bug is fixed just now. This didn't depend on number of refs and assemblies (I hope nothing more is dependent on it), this was caused by another rare case: everything aligned, so there were no report for "not_aligned_quast_output" at all. Now we process this situation correctly!

**Comment by pbelmann** [comment] 2015-08-05 08:02
thx it works now :+1:
