### ISSUE TITLE
Question about misassemblies; Sum does not add up.

### ISSUE THREAD

**Issue by Unaimend** [ablab/quast#158] opened 2021-02-01 15:33 UTC
So in this report MetaQuast reports 18 translocation but when I look at the data for each genome MetaQuast reports over 200 translocations. Could somebody explain me what is going on there.
Where does the number of 18 translocations come from?

![2021-02-01-162914_480x123_scrot](https://user-images.githubusercontent.com/7808379/106479696-e4285b00-64aa-11eb-9a1a-e72ec44ad4bf.png)
![2021-02-01-162921_358x65_scrot](https://user-images.githubusercontent.com/7808379/106479701-e5598800-64aa-11eb-8c77-0ac81a170594.png)

And I think its pretty confusing that the number of misassemblies in the graph  does not match the number of reported misassemblies in the summarized statistics.
![2021-02-01-162822_384x120_scrot](https://user-images.githubusercontent.com/7808379/106479828-0ae69180-64ab-11eb-81ab-fee9846e22bc.png)
![2021-02-01-162848_1920x1080_scrot](https://user-images.githubusercontent.com/7808379/106479856-12a63600-64ab-11eb-8298-ed3904e29eca.png)

![2021-02-01-163246_1470x648_scrot](https://user-images.githubusercontent.com/7808379/106479917-205bbb80-64ab-11eb-95ba-de4da2e8baba.png)

**Comment by alexeigurevich** [comment] 2021-02-05 15:29
Hi!
I agree that it could be a bit confusing but here is the explanation.

Simplified, MetaQuast works as a three-step pipeline:
1. Align an assembly to the combined reference (i.e. concatenation of all single-organism references into a single large "meta-reference"). In this alignment, we allow ambiguous mapping by default (to disable, please use the `--unique-mapping` option). That is, a single contig may [fully or partially] map to several fragments on the combined reference with very similar mapping quality, e.g. it may map to several distinct organisms inside the combined reference. This is a common thing if there are multiple closely-related species/strains in the set of reference genomes. Also, by default, we use relatively relaxed mapping settings of the embedded third-party aligner (minimap2) in this step in Quast v.5.0. 
2. All contigs are attributed as related to R1, R2, .. Rn single-organism references based on their alignments on step 1. If a contig has at least a small alignment to a combined reference fragment corresponding to single-organism reference Ri it is marked as "related to Ri". Note: each contig may be related to many references simultaneously.
3. For each Ri in the set of single-organism references, we collect all contigs related to this reference and form the "assembly_aligned_to_Ri" subset of the initial input assembly. This assembly_aligned_to_Ri is evaluated against Ri using regular Quast run. By default, it uses relatively strict mapping settings and allows only one mapping per contig fragment (to change this to allow ambiguous alignments you can use the `--ambiguity all' option).

As a result, we have a Quast report for the combined reference and multiple Quast reports per each single-organism reference (and one more small report for contigs not aligned anywhere). They are combined together in the report.html you are quoting in the following manner. 
The unexpanded values in the report (near a plus sign, with white background) are corresponding values from the combined reference report; expanded values (when you press on the plus sign and see rows with grey background) are from per-reference reports. And they are not necessarily summed up. E.g. if you look at the Total length metric, the sum of per-reference values is almost always larger than the combined report value since some contigs are counted more than once (attributed to more than one single-organism references due to their genome similarities). 

This "not summed up" observation is especially true if we talk about misassemblies. E.g. you have a contig that combines two fragments from two distinct genomes. In the combined report, this contig will produce an inter-species misassembly while in the two per-reference reports this contig will be just a partially unaligned contig without any misassembly. Controversially, if there are closely related species A and B in the sample, a contig may be related to species A but on steps (1-2) of the pipeline be attributed to species B as well. As a result, its evaluation against B on step (3) will result in many misassemblies caused by true variations between A and B. Thus, in the combined report there will be a few misassemblies in total (against the combined reference) while you may see a lot of misassemblies against reference B and a few against reference A in the expanded list.

--
The misassemblies plot depicts per-reference misassemblies numbers, that is the values shown on the grey background after expanding the `# misassemblies` row.

**Closed by alexeigurevich** 2021-02-05 15:29 UTC

**Comment by Unaimend** [comment] 2021-02-06 20:10
Thank you very much for this detailed explanation. Don't you guys think it would make sense to make all the explanations of the statistics a little bit more helpful?

Regards, Thomas Dost
