### ISSUE TITLE
circos: incomplete genes.txt file

### ISSUE THREAD

**Issue by webbchen** [ablab/quast#37] opened 2017-08-30 11:09 UTC
Dear developers,
When making a circus diagram the genes.txt file which is created contains only data for just under half of the reference chromosomes supplied. predictably, the gene track in the diagram is incomplete. I checked the raw annotation file (gff3), but this one is complete.
Kind regards,

Anne

![circos](https://user-images.githubusercontent.com/12898402/29869712-03ebf370-8d7c-11e7-9e6e-383fc79d4226.png)

**Comment by alexeigurevich** [comment] 2017-08-30 11:21
Hi Anne,
Could you please upload your quast.log, annotation file (gff) and reference file for debugging. You can privately send them to quast.support@cab.spbu.ru
I suppose that the problem is related to inconsistency of gff chromosome names and names in the reference file, or GFF feature field is not "gene" for some entries.
Best,
Alexey

**Comment by webbchen** [comment] 2017-08-30 12:24
Hi Alexey

I've sent the files per email. Many thanks for looking into this!

Kind regards,
Anne

**Comment by alexeigurevich** [comment] 2017-09-07 11:43
I will just copy the answer sent by email (for the other users having similar problems) and close the issue.

To avoid possible confusion, Quast requires that the sequence names in the annotation have to fully match sequence names in the reference file. For example, you should use either "ENA|CM001196|CM001196.1 Mycosphaerella graminicola IPO323 chromosome 1, whole genome shotgun sequence." or "1" in both files. Try to correspondingly change the reference or the gff file and rerun Quast using the latest version from the master branch.

**Closed by alexeigurevich** 2017-09-07 11:43 UTC

**Comment by webbchen** [comment] 2017-09-08 12:06
Renaming the chromosomes to match the names in the gff file and using the latest scripts from the master branch did work, the problems with parsing the genes have gone away. Many thanks for that!
