### ISSUE TITLE
Error when running ./setup.py test

### ISSUE THREAD

**Issue by morispi** [ablab/quast#154] opened 2020-09-24 11:54 UTC
Hello,

I'm trying to use quast, and the tool reports an error when attempting to run the test.
The quast.log file is attached here: [quast.log](https://github.com/ablab/quast/files/5275627/quast.log)
I'm using the latest version of quast, cloned today.

Installation reported the following message:

    QUAST version 5.1.0rc1 installation complete.

    The full package is installed, with the features for reference
    sequence detection in MetaQUAST, and structural variant detection
    for misassembly events refinement.

But nevertheless, a few errors were reported during the installation (probably because I'm using Python3?). See the errors below in the attached file: [installErrors.log](https://github.com/ablab/quast/files/5275671/installErrors.log)

What should I do in order to get quast to run properly? It seems like there is an issue with the alignment step, so I guess it have something to do with Minimap2, but it seems to be properly installed and able to run when i switch to `quast_libs/minimap2/`

Any insight on this?

Thanks in advance.

Best,
Pierre

**Comment by alexeigurevich** [comment] 2020-09-24 12:42
Hi Pierre,

Yes, you can ignore error messages in installError.log since they are actually warnings and indeed related to Python3. Our package includes some Python2-only files for embedded third-party libs but they are not really used if the script is executed with Python3 (and vice versa).

The issue is rather strange and we can't say for sure what is causing it. Let's try to find what is going wrong. Could you please run 
`./quast.py --test -t1`
And send us the `quast.log` file?  In this case (`-t 1`), there will be no parallelization (`joblib`), so maybe the error message would be more clear.

**Comment by morispi** [comment] 2020-09-24 12:44
Hi,

Thanks for the quick answer!
Here's the log file: [quast.log](https://github.com/ablab/quast/files/5276054/quast.log)

**Comment by morispi** [comment] 2020-09-24 13:02
Seems like I actually fixed my issue.

I removed the minimap2 from in `quast_libs`, downloaded it again, and manually ran minimap2 installation from there. I then attempted to run `./quast.py --test` again and everything passed.

Sorry for bothering with the issue, I don't know what exactly went wrong with minimap2. It had some issues compiling on the cluster I'm working on, so I probably made some weird fixes to get it to compile. Still not exactly sure why it did compile but couldn't work with quast though...

Thanks for the super fast answer/support anyway! And sorry again for bothering.

Best,
Pierre

**Comment by alexeigurevich** [comment] 2020-09-24 13:18
Great to hear that!

> And sorry again for bothering.
No problem at all, please post issues if something is not working -- it may help other users to solve the same problems in the future.
By the way, it seems that we found a related bug on our side. So your issue report is useful for us, too. 
We should (a) better check minimap2 availability and correctness, (b) report a clear error/warning message if something is not working instead of crashing. I will push the fixes and close the issue afterward.

**Closed** 2022-05-26 11:11 UTC
